"""RunPod backend for cloud GPU processing."""

import subprocess
import json
from pathlib import Path
from typing import Optional, Dict, Any

from ..models.base import StyleTransferModel
from ..utils.logger import get_logger


class RunPodBackend:
    """Process videos on RunPod cloud GPUs."""
    
    def __init__(self):
        self.logger = get_logger(__name__)
        self.runpod_config = self._load_runpod_config()
    
    def process_video(self, input_path: Path, output_path: Path,
                     model: StyleTransferModel, fps: int, resize: int,
                     keep_audio: bool = True) -> bool:
        """Process video on RunPod."""
        try:
            self.logger.info("☁️  Setting up RunPod processing")
            
            if not self.runpod_config:
                self._setup_runpod_instructions(input_path, output_path, model.model_name, fps, resize, keep_audio)
                return True
            
            # TODO: Implement RunPod API integration
            self.logger.warning("RunPod API integration not yet implemented")
            self._setup_runpod_instructions(input_path, output_path, model.model_name, fps, resize, keep_audio)
            
            return True
            
        except Exception as e:
            self.logger.error(f"❌ RunPod setup failed: {e}")
            return False
    
    def _load_runpod_config(self) -> Optional[Dict[str, Any]]:
        """Load RunPod configuration if available."""
        config_path = Path.home() / ".runpod" / "config.json"
        if config_path.exists():
            try:
                with open(config_path) as f:
                    return json.load(f)
            except Exception:
                pass
        return None
    
    def _setup_runpod_instructions(self, input_path: Path, output_path: Path,
                                  model_name: str, fps: int, resize: int, keep_audio: bool):
        """Provide instructions for manual RunPod setup."""
        
        print("\n" + "="*60)
        print("🚀 RUNPOD PROCESSING SETUP")
        print("="*60)
        print("1. Create a RunPod instance with PyTorch template")
        print("2. SSH into your RunPod instance:")
        print("   ssh root@<your-pod-ip>")
        print()
        print("3. Install the stylize-video tool:")
        print("   git clone https://github.com/your-repo/stylize-video.git")
        print("   cd stylize-video")
        print("   pip install -r requirements.txt")
        print()
        print("4. Upload your input video:")
        print(f"   scp {input_path} root@<your-pod-ip>:~/stylize-video/")
        print()
        print("5. Run the processing command:")
        command = (f"   python -m stylize_video stylize "
                  f"--input {input_path.name} "
                  f"--output {output_path.name} "
                  f"--model {model_name} "
                  f"--backend local "
                  f"--fps {fps} "
                  f"--resize {resize} "
                  f"{'--keep-audio' if keep_audio else '--no-audio'} "
                  f"--verbose")
        print(command)
        print()
        print("6. Download the result:")
        print(f"   scp root@<your-pod-ip>:~/stylize-video/{output_path.name} ./")
        print("="*60)
    
    def create_runpod_script(self, input_path: Path, output_path: Path,
                           model_name: str, fps: int, resize: int, keep_audio: bool) -> Path:
        """Create a bash script for RunPod execution."""
        
        script_content = f"""#!/bin/bash
# RunPod Style Transfer Processing Script
# Generated by stylize-video CLI

set -e

echo "🚀 Starting RunPod style transfer processing..."

# Update system
apt-get update && apt-get install -y ffmpeg

# Install Python dependencies
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install opencv-python moviepy pillow tqdm click colorama

# Clone repository (if not already present)
if [ ! -d "stylize-video" ]; then
    git clone https://github.com/your-repo/stylize-video.git
fi

cd stylize-video

# Run processing
python -m stylize_video stylize \\
  --input {input_path.name} \\
  --output {output_path.name} \\
  --model {model_name} \\
  --backend local \\
  --fps {fps} \\
  --resize {resize} \\
  {'--keep-audio' if keep_audio else '--no-audio'} \\
  --verbose

echo "✅ Processing completed!"
echo "Download your result: {output_path.name}"
"""
        
        script_path = Path("runpod_process.sh")
        with open(script_path, 'w') as f:
            f.write(script_content)
        
        # Make executable
        script_path.chmod(0o755)
        
        self.logger.info(f"Created RunPod script: {script_path}")
        return script_path
